name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test Action
        uses: ./
        with:
          repository: nodes-app/action-add-org-secrets
          secrets: |
            EXAMPLE_SECRET
          token: ${{ secrets.GH_ACCESS_TOKEN }}
